version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(filename)s - %(lineno)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    webdriver_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/webdriver.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    redis_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/redis.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    rabbit_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/rabbit.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    webdriver_module:
        level: INFO
        handlers: [webdriver_handler]
        propagate: no
    redis_module:
        level: INFO
        handlers: [redis_handler]
        propagate: no
    rabbit_module:
        level: INFO
        handlers: [rabbit_handler]
        propagate: no

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]